import { createHash } from "node:crypto";
import { mkdir, readFile, rm, writeFile } from "node:fs/promises";
import path from "node:path";

const root = process.cwd();
const sourcePath = path.join(root, "public", "data", "pdf-image-quiz.json");
const outputRoot = path.join(root, "public", "data", "question-shards");
const manifestPath = path.join(root, "public", "data", "question-release-manifest.json");
const generatedReleasePath = path.join(root, "src", "generated", "questionRelease.ts");
const checkOnly = process.argv.includes("--check");

type Chapter = {
  bankId: string;
  bankTitle: string;
  chapterId: string;
  chapterTitle: string;
  chapterSlug: string;
  sourceFile: string;
  questionCount: number;
  questions: unknown[];
};

type Bank = { bankId: string; bankTitle: string; chapters: Chapter[] };
type SourceData = { banks: Bank[] };

type Manifest = {
  schemaVersion: 1;
  releaseId: string;
  sourceHash: string;
  generatedAt: string;
  totalQuestions: number;
  banks: Array<{
    bankId: string;
    bankTitle: string;
    questionCount: number;
    chapters: Array<{
      chapterId: string;
      chapterTitle: string;
      chapterSlug: string;
      sourceFile: string;
      questionCount: number;
      path: string;
      hash: string;
      bytes: number;
    }>;
  }>;
};

function stableJson(value: unknown): string {
  return `${JSON.stringify(value)}\n`;
}

function sha256(value: string | Buffer): string {
  return createHash("sha256").update(value).digest("hex");
}

function safeSegment(value: string): string {
  return value.replace(/[^A-Za-z0-9._-]+/g, "-").replace(/^-+|-+$/g, "") || "chapter";
}

async function build(): Promise<{ manifest: Manifest; files: Map<string, string> }> {
  const raw = await readFile(sourcePath);
  const data = JSON.parse(raw.toString("utf8")) as SourceData;
  const sourceHash = sha256(raw);
  const files = new Map<string, string>();
  let totalQuestions = 0;

  const banks = data.banks.map((bank) => {
    let bankQuestionCount = 0;
    const chapters = bank.chapters.map((chapter) => {
      const payload = { bankId: bank.bankId, bankTitle: bank.bankTitle, chapter };
      const content = stableJson(payload);
      const relativePath = `data/question-shards/${safeSegment(bank.bankId)}/${safeSegment(chapter.chapterSlug || chapter.chapterId)}.json`;
      files.set(relativePath, content);
      const questionCount = chapter.questions.length;
      bankQuestionCount += questionCount;
      totalQuestions += questionCount;
      return {
        chapterId: chapter.chapterId,
        chapterTitle: chapter.chapterTitle,
        chapterSlug: chapter.chapterSlug,
        sourceFile: chapter.sourceFile,
        questionCount,
        path: relativePath,
        hash: sha256(content),
        bytes: Buffer.byteLength(content),
      };
    });
    return { bankId: bank.bankId, bankTitle: bank.bankTitle, questionCount: bankQuestionCount, chapters };
  });

  const manifest: Manifest = {
    schemaVersion: 1,
    releaseId: sourceHash.slice(0, 16),
    sourceHash,
    generatedAt: new Date(0).toISOString(),
    totalQuestions,
    banks,
  };
  return { manifest, files };
}

async function verifyFile(filePath: string, expected: string): Promise<void> {
  const actual = await readFile(filePath, "utf8").catch(() => "");
  if (actual !== expected) throw new Error(`Generated question shard is stale: ${path.relative(root, filePath)}`);
}

async function main(): Promise<void> {
  const { manifest, files } = await build();
  const manifestContent = stableJson(manifest);
  const generatedReleaseContent = `// Generated by scripts/generate-question-shards.ts. Do not edit.\nexport const QUESTION_RELEASE_ID = ${JSON.stringify(manifest.releaseId)};\n`;

  if (checkOnly) {
    await verifyFile(manifestPath, manifestContent);
    await verifyFile(generatedReleasePath, generatedReleaseContent);
    for (const [relativePath, content] of files) await verifyFile(path.join(root, "public", relativePath), content);
    console.log(`Question shard manifest verified: ${manifest.totalQuestions} questions, ${files.size} chapter shards`);
    return;
  }

  await rm(outputRoot, { recursive: true, force: true });
  for (const [relativePath, content] of files) {
    const target = path.join(root, "public", relativePath);
    await mkdir(path.dirname(target), { recursive: true });
    await writeFile(target, content, "utf8");
  }
  await writeFile(manifestPath, manifestContent, "utf8");
  await mkdir(path.dirname(generatedReleasePath), { recursive: true });
  await writeFile(generatedReleasePath, generatedReleaseContent, "utf8");
  console.log(`Question shards generated: ${manifest.totalQuestions} questions, ${files.size} chapter shards, release ${manifest.releaseId}`);
}

void main();
